### ISSUE TITLE
version 8.3

### ISSUE THREAD

**Issue by eduardomrj** [cmbsolutions/nppRandomStringGenerator#11]
incompatible

**Comment by cmbsolutions** [comment]
Thanks, i will look in to it asap.

**Comment by cmbsolutions** [comment]
@eduardomrj it is running fine in notepad++ 8.4.2 x86 and x64

8.3 had some critical issues, the notepad++ team advised to use 8.3.1 see [here](https://notepad-plus-plus.org/downloads/v8.3/)

**Comment by cmbsolutions** [comment]
If you still get "incompatible" with 8.4.2 please let me know
