### ISSUE TITLE
Include symbols line - 2 issues[BUG]

### ISSUE THREAD

**Issue by Lrt19** [cmbsolutions/nppRandomStringGenerator#13]
First, great work on the plugin, very useful.
The default characters in the "Include symbols" line has semicolon twice, therefor the frequency distribution of ; will be twice that of the other characters.
Also, the generated code seems to ignore the last character on the "Include symbols" line. It will get 0 frequency. (default tilde ~)
Please keep the functionality where a user can type anything here, even multiple repeating letters to purposely skew the frequency distribution.
I could see use in this to hide a message in apparent randomness.
As an enhancement request; could it be possible for the plugin to save the users last settings?
Thank you!

using v1.4.0

**Comment by cmbsolutions** [comment]
Hi, i will open a new issue with the enhancement request of saving the user last settings

**Comment by cmbsolutions** [comment]
@Lrt19 the enhancement is added in v1.6.0 
See https://github.com/cmbsolutions/nppRandomStringGenerator/issues/15
