### ISSUE TITLE
[BUG] Misplaced interface

### ISSUE THREAD

**Issue by amaoo** [cmbsolutions/nppRandomStringGenerator#19]
**Describe the bug**
Misplaced interface

**To Reproduce**
1. Click on 'Config & Generate'

**Screenshots**
![image](https://github.com/cmbsolutions/nppRandomStringGenerator/assets/80802781/a2cb9c52-1e78-449c-bf97-4992ba3784dd)

**Desktop (please complete the following information):**
 - OS: [windows10 22H2]
 - Instruction Set: [x64]
 - Notepad++ version [8.5.3.x64]
 - Plugin version [1.6.0.x64]

**Comment by cmbsolutions** [comment]
@amaoo That looks like it is missing the font that is used on the formcontrols. The font is SegoeUI, which should be available in windows 10.

I will check 2night if this is the case by deleting the font on my machine.

**Comment by amaoo** [comment]
@cmbsolutions 
v1.6.1 I tested here is normal, thank you very much for the quick fix.
