### ISSUE TITLE
plugin crash in runPluginCommand(size_t i : 57)

### ISSUE THREAD

**Issue by esnon** [cmbsolutions/nppRandomStringGenerator#26]
Sorry for making this hard, just trying to remove limit and double the max quantity, nothing strange.
And then my curious made up to 102400 and then crash as screenshot.
**I've tried uninstall and reinstall the plugin and also same as notepad, but still crash**

![crash limit remove](https://github.com/cmbsolutions/nppRandomStringGenerator/assets/95175440/fc02a6e9-3808-4969-b6cd-3ee0aca9fe09)

**Comment by cmbsolutions** [comment]
@esnon It is fixed, you should be able to run it again.
