### ISSUE TITLE
IDEA: extend random string generator with UUID generator

### ISSUE THREAD

**Issue by RobTillaart** [cmbsolutions/nppRandomStringGenerator#29]
UUID's are random strings with a defined format used in programming for different purposes e.g. object ID's or session ID's etc.
They look like HEX numbers with hyphens e.g. "550e8400-e29b-41d4-a716-446655440000".

There are some variants and these are relative easy to implement.
Details see: https://en.wikipedia.org/wiki/Universally_unique_identifier

It might be a logical extension for the nppRandomStringGenerator, if not just close the issue.

**Comment by cmbsolutions** [comment]
@RobTillaart will look into that, shouldn't be much work to add it.
